/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => CardBoxPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian11 = require("obsidian");

// src/settings.ts
var import_obsidian = require("obsidian");

// src/i18n.ts
var i18n = {
  // 导航 / 命令
  capture: "\u5FEB\u901F\u8BB0\u5F55\u5361\u7247",
  openMain: "\u6253\u5F00\u5361\u7247\u76D2\u89C6\u56FE",
  mergeSelected: "\u5408\u5E76\u6240\u9009\u5361\u7247\u4E3A\u6587\u7AE0",
  batchTag: "\u6279\u91CF\u6253\u6807\u7B7E",
  archiveSelected: "\u5F52\u6863\u6240\u9009\u5361\u7247",
  deleteSelected: "\u5220\u9664\u6240\u9009\u5361\u7247",
  toggleSelect: "\u5207\u6362\u591A\u9009\u6A21\u5F0F",
  // 视图
  viewTitle: "\u5361\u7247\u76D2",
  indexing: "\u7D22\u5F15\u4E2D\u2026",
  empty: "\u8FD8\u6CA1\u6709\u5361\u7247\u3002\u70B9\u51FB\u300C+\u300D\u6216\u4F7F\u7528\u300C\u5FEB\u901F\u8BB0\u5F55\u5361\u7247\u300D\u547D\u4EE4\u5F00\u59CB\u6536\u96C6\u7075\u611F\u3002",
  noMatch: "\u6CA1\u6709\u7B26\u5408\u6761\u4EF6\u7684\u5361\u7247",
  cardMode: "\u5361\u7247",
  timelineMode: "\u65F6\u95F4\u7EBF",
  searchPlaceholder: "\u641C\u7D22\u5361\u7247\u2026",
  hasTag: "\u6709\u6807\u7B7E",
  noTag: "\u65E0\u6807\u7B7E",
  emptyContent: "\u7A7A\u5185\u5BB9",
  hasTask: "\u542B\u4EFB\u52A1",
  showArchived: "\u542B\u5F52\u6863",
  moreTags: "\uFF0B\u6807\u7B7E",
  selectedCount: (n) => `\u5DF2\u9009 ${n}`,
  tagSelected: "\u6253\u6807\u7B7E",
  mergeSelectedAction: "\u5408\u5E76\u4E3A\u6587\u7AE0",
  archiveSelectedAction: "\u5F52\u6863",
  deleteSelectedAction: "\u5220\u9664",
  cancelSelect: "\u53D6\u6D88\u9009\u62E9",
  newCard: "\u65B0\u5EFA\u5361\u7247",
  more: "\u66F4\u591A\u64CD\u4F5C",
  // 卡片操作菜单
  edit: "\u7F16\u8F91",
  addChild: "\u521B\u5EFA\u5B50\u5361\u7247",
  tag: "\u6253\u6807\u7B7E",
  archive: "\u5F52\u6863",
  unarchive: "\u53D6\u6D88\u5F52\u6863",
  delete: "\u5220\u9664",
  expandChildren: "\u5C55\u5F00\u5B50\u5361\u7247",
  collapseChildren: "\u6536\u8D77\u5B50\u5361\u7247",
  childCount: (n) => `${n} \u5F20\u5B50\u5361\u7247`,
  // 时间
  today: "\u4ECA\u5929",
  yesterday: "\u6628\u5929",
  archivedIndicator: "\u5DF2\u5F52\u6863",
  taskIndicator: "\u542B\u4EFB\u52A1",
  // 快速捕获
  captureTitle: "\u8BB0\u5F55\u5361\u7247",
  capturePlaceholder: "\u8F93\u5165\u5361\u7247\u5185\u5BB9\u2026",
  continuousMode: "\u8FDE\u7EED\u6A21\u5F0F",
  save: "\u4FDD\u5B58",
  cancel: "\u53D6\u6D88",
  emptyCaptureHint: "\u5185\u5BB9\u4E3A\u7A7A\uFF0C\u672A\u4FDD\u5B58",
  childCapturePlaceholder: "\u8F93\u5165\u5B50\u5361\u7247\u5185\u5BB9\u2026",
  // 合并成文
  mergeTitle: "\u5408\u5E76\u4E3A\u6587\u7AE0",
  articleTitleLabel: "\u6587\u7AE0\u6807\u9898",
  articleTitlePlaceholder: "\u8F93\u5165\u6587\u7AE0\u6807\u9898",
  mergeModeLabel: "\u5408\u5E76\u6A21\u5F0F",
  mergeModeSimple: "\u7B80\u5355\u62FC\u63A5",
  mergeModeHeadings: "\u6309\u6807\u9898\u5C42\u7EA7",
  mergeButton: "\u751F\u6210\u6587\u7AE0",
  mergedNotice: (title) => `\u5DF2\u751F\u6210\u6587\u7AE0\uFF1A${title}`,
  // 批量标签
  tagTitle: "\u6253\u6807\u7B7E",
  tagPlaceholder: "\u8F93\u5165\u6807\u7B7E\uFF08\u652F\u6301 \u7236/\u5B50 \u5D4C\u5957\uFF09",
  existingTags: "\u5DF2\u6709\u6807\u7B7E\uFF08\u70B9\u51FB\u6DFB\u52A0\uFF09",
  apply: "\u5E94\u7528",
  tagApplied: (n, tag) => `\u5DF2\u4E3A ${n} \u5F20\u5361\u7247\u6DFB\u52A0\u6807\u7B7E #${tag}`,
  // 确认
  confirmTitle: "\u786E\u8BA4\u64CD\u4F5C",
  confirmDeleteText: (n) => `\u786E\u5B9A\u5220\u9664\u6240\u9009 ${n} \u5F20\u5361\u7247\u5417\uFF1F\u5220\u9664\u540E\u4F1A\u8FDB\u5165\u56DE\u6536\u7AD9\u3002`,
  confirmArchiveText: (n) => `\u786E\u5B9A\u5F52\u6863\u6240\u9009 ${n} \u5F20\u5361\u7247\u5417\uFF1F`,
  confirm: "\u786E\u8BA4",
  // 设置
  settingsTitle: "CardBox \u8BBE\u7F6E",
  cardsFolderName: "\u5361\u7247\u5B58\u653E\u6587\u4EF6\u5939",
  cardsFolderDesc: "\u5361\u7247\u7B14\u8BB0\u5B58\u653E\u7684\u6587\u4EF6\u5939\uFF08\u76F8\u5BF9 Vault \u6839\uFF0C\u65E0\u9700\u9996\u5C3E\u659C\u6760\uFF09\u3002\u6539\u52A8\u540E\u81EA\u52A8\u91CD\u5EFA\u7D22\u5F15\u3002",
  mergeFolderName: "\u5408\u5E76\u8F93\u51FA\u6587\u4EF6\u5939",
  mergeFolderDesc: "\u300C\u5408\u5E76\u4E3A\u6587\u7AE0\u300D\u751F\u6210\u7684\u65B0\u7B14\u8BB0\u5B58\u653E\u4F4D\u7F6E\u3002",
  defaultTagsName: "\u65B0\u5EFA\u5361\u7247\u9ED8\u8BA4\u6807\u7B7E",
  viewModeName: "\u9ED8\u8BA4\u89C6\u56FE",
  sortName: "\u9ED8\u8BA4\u6392\u5E8F",
  sortCreatedDesc: "\u521B\u5EFA\u65F6\u95F4 \u2193",
  sortCreatedAsc: "\u521B\u5EFA\u65F6\u95F4 \u2191",
  sortUpdatedDesc: "\u66F4\u65B0\u65F6\u95F4 \u2193",
  sortTitle: "\u6807\u9898",
  continuousName: "\u8FDE\u7EED\u6A21\u5F0F\u9ED8\u8BA4\u5F00\u542F",
  continuousDesc: "\u5FEB\u901F\u8BB0\u5F55\u65F6\u4FDD\u5B58\u540E\u4FDD\u6301\u6253\u5F00\u5E76\u6E05\u7A7A\u8F93\u5165\u6846\uFF0C\u65B9\u4FBF\u8FDE\u7EED\u5F55\u5165\u7075\u611F\u3002",
  showArchivedName: "\u5361\u7247\u76D2\u4E2D\u663E\u793A\u5F52\u6863\u5361\u7247",
  showArchivedDesc: "\u5173\u95ED\u65F6\u5F52\u6863\u5361\u7247\u4E0D\u51FA\u73B0\u5728\u5361\u7247\u76D2\u4E2D\u3002",
  archiveMethodName: "\u5F52\u6863\u65B9\u5F0F",
  archiveMethodDesc: "MVP \u4F7F\u7528 frontmatter \u6807\u8BB0\u5F52\u6863\uFF1A\u4E0D\u79FB\u52A8\u6587\u4EF6\u3001\u4E0D\u7834\u574F\u53CC\u5411\u94FE\u63A5\uFF0C\u968F\u65F6\u53EF\u9006\u3002",
  folderPlaceholder: "\u4F8B\u5982 Cards",
  addTag: "\u6DFB\u52A0\u6807\u7B7E",
  tagInputPlaceholder: "\u8F93\u5165\u6807\u7B7E\u540E\u56DE\u8F66",
  // 通知
  noticeFolderCreated: (folder) => `\u5361\u7247\u6587\u4EF6\u5939\u4E0D\u5B58\u5728\uFF0C\u5DF2\u521B\u5EFA\uFF1A${folder}`,
  childCreated: "\u5DF2\u521B\u5EFA\u5B50\u5361\u7247"
};

// src/settings.ts
var DEFAULT_SETTINGS = {
  cardsFolder: "Cards",
  mergeOutputFolder: "Cards",
  filenameFormat: "datetime",
  defaultTags: [],
  defaultViewMode: "card",
  defaultSort: "created-desc",
  continuousCaptureDefault: true,
  showArchived: false,
  archiveMethod: "flag"
};
var CardBoxSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, access) {
    super(app, access);
    this.access = access;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: i18n.settingsTitle });
    const s = this.access.settings;
    new import_obsidian.Setting(containerEl).setName(i18n.cardsFolderName).setDesc(i18n.cardsFolderDesc).addText((text) => {
      text.setPlaceholder(i18n.folderPlaceholder).setValue(s.cardsFolder).onChange(async (value) => {
        s.cardsFolder = value.trim().replace(/^\/+|\/+$/g, "");
        await this.access.saveSettings();
        this.access.onFolderChanged();
      });
    });
    new import_obsidian.Setting(containerEl).setName(i18n.mergeFolderName).setDesc(i18n.mergeFolderDesc).addText((text) => {
      text.setPlaceholder(i18n.folderPlaceholder).setValue(s.mergeOutputFolder).onChange(async (value) => {
        s.mergeOutputFolder = value.trim().replace(/^\/+|\/+$/g, "");
        await this.access.saveSettings();
      });
    });
    new import_obsidian.Setting(containerEl).setName(i18n.defaultTagsName).addText((text) => {
      text.setPlaceholder(i18n.tagInputPlaceholder);
      text.inputEl.addEventListener("keydown", (e) => {
        if (e.key !== "Enter") return;
        e.preventDefault();
        const tag = text.getValue().trim().replace(/^#/, "");
        if (!tag) return;
        s.defaultTags = [.../* @__PURE__ */ new Set([...s.defaultTags, tag])];
        text.setValue("");
        this.renderTags();
        void this.access.saveSettings();
      });
    });
    this.tagsEl = containerEl.createDiv({ cls: "cardbox-setting-tags" });
    this.renderTags();
    new import_obsidian.Setting(containerEl).setName(i18n.viewModeName).addDropdown((dd) => {
      dd.addOption("card", i18n.cardMode).addOption("timeline", i18n.timelineMode).setValue(s.defaultViewMode).onChange(async (v) => {
        s.defaultViewMode = v;
        await this.access.saveSettings();
      });
    });
    new import_obsidian.Setting(containerEl).setName(i18n.sortName).addDropdown((dd) => {
      dd.addOption("created-desc", i18n.sortCreatedDesc).addOption("created-asc", i18n.sortCreatedAsc).addOption("updated-desc", i18n.sortUpdatedDesc).addOption("title", i18n.sortTitle).setValue(s.defaultSort).onChange(async (v) => {
        s.defaultSort = v;
        await this.access.saveSettings();
      });
    });
    new import_obsidian.Setting(containerEl).setName(i18n.continuousName).setDesc(i18n.continuousDesc).addToggle((t) => {
      t.setValue(s.continuousCaptureDefault).onChange(async (v) => {
        s.continuousCaptureDefault = v;
        await this.access.saveSettings();
      });
    });
    new import_obsidian.Setting(containerEl).setName(i18n.showArchivedName).setDesc(i18n.showArchivedDesc).addToggle((t) => {
      t.setValue(s.showArchived).onChange(async (v) => {
        s.showArchived = v;
        await this.access.saveSettings();
      });
    });
    new import_obsidian.Setting(containerEl).setName(i18n.archiveMethodName).setDesc(i18n.archiveMethodDesc);
  }
  renderTags() {
    this.tagsEl.empty();
    for (const tag of this.access.settings.defaultTags) {
      const chip = this.tagsEl.createSpan({ cls: "cardbox-chip" });
      chip.setText(`#${tag}`);
      const remove = chip.createSpan({ cls: "cardbox-chip-remove", text: "\xD7" });
      remove.onclick = async () => {
        this.access.settings.defaultTags = this.access.settings.defaultTags.filter((t) => t !== tag);
        this.renderTags();
        await this.access.saveSettings();
      };
    }
  }
};

// src/frontmatter.ts
var import_obsidian2 = require("obsidian");

// src/utils/format.ts
function pad2(n) {
  return String(n).padStart(2, "0");
}
function randomHex(len) {
  let s = "";
  for (let i = 0; i < len; i++) s += Math.floor(Math.random() * 16).toString(16);
  return s;
}
function generateId(ts = Date.now()) {
  const d = new Date(ts);
  const date = `${d.getFullYear()}-${pad2(d.getMonth() + 1)}-${pad2(d.getDate())}`;
  const time = `${pad2(d.getHours())}${pad2(d.getMinutes())}${pad2(d.getSeconds())}`;
  return `${date}-${time}-${randomHex(3)}`;
}
function toDayKey(ts) {
  const d = new Date(ts);
  return `${d.getFullYear()}-${pad2(d.getMonth() + 1)}-${pad2(d.getDate())}`;
}
function dayDiff(ts, now) {
  const a = (/* @__PURE__ */ new Date(toDayKey(ts) + "T00:00:00")).getTime();
  const b = (/* @__PURE__ */ new Date(toDayKey(now) + "T00:00:00")).getTime();
  return Math.round((b - a) / 864e5);
}
function formatTimeHM(ts) {
  const d = new Date(ts);
  return `${pad2(d.getHours())}:${pad2(d.getMinutes())}`;
}
function formatRelativeTime(ts, now = Date.now()) {
  const diff = dayDiff(ts, now);
  if (diff === 0) return `${i18n.today} ${formatTimeHM(ts)}`;
  if (diff === 1) return `${i18n.yesterday} ${formatTimeHM(ts)}`;
  const d = new Date(ts);
  if (d.getFullYear() === new Date(now).getFullYear()) return `${d.getMonth() + 1}\u6708${d.getDate()}\u65E5`;
  return `${d.getFullYear()}\u5E74${d.getMonth() + 1}\u6708${d.getDate()}\u65E5`;
}
function formatDayHeader(ts, now = Date.now()) {
  const diff = dayDiff(ts, now);
  if (diff === 0) return i18n.today;
  if (diff === 1) return i18n.yesterday;
  const d = new Date(ts);
  const weekdays = ["\u5468\u65E5", "\u5468\u4E00", "\u5468\u4E8C", "\u5468\u4E09", "\u5468\u56DB", "\u5468\u4E94", "\u5468\u516D"];
  const weekday = weekdays[d.getDay()];
  if (d.getFullYear() === new Date(now).getFullYear()) return `${d.getMonth() + 1}\u6708${d.getDate()}\u65E5\uFF08${weekday}\uFF09`;
  return `${d.getFullYear()}\u5E74${d.getMonth() + 1}\u6708${d.getDate()}\u65E5\uFF08${weekday}\uFF09`;
}
function sanitizeFileName(title) {
  return title.replace(/[\\/:*?"<>|]/g, "").trim().replace(/\s+/g, " ").slice(0, 80);
}
function normalizeTag(tag) {
  if (typeof tag !== "string") return "";
  return tag.trim().replace(/^#/, "").replace(/\/+/g, "/").replace(/^\/+|\/+$/g, "");
}
function normalizeTags(tags) {
  const list = Array.isArray(tags) ? tags : typeof tags === "string" ? [tags] : [];
  const out = [];
  for (const t of list) {
    const n = normalizeTag(t);
    if (n && !out.includes(n)) out.push(n);
  }
  return out;
}

// src/frontmatter.ts
var SNIPPET_LENGTH = 200;
function splitFrontmatter(content) {
  const m = /^---\r?\n([\s\S]*?)\r?\n---(?:\r?\n|$)/.exec(content);
  if (m) {
    try {
      const parsed = (0, import_obsidian2.parseYaml)(m[1]);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        return { data: parsed, body: content.slice(m[0].length) };
      }
    } catch (e) {
    }
  }
  return { data: null, body: content };
}
function buildCardContent(fm, body) {
  return `---
${(0, import_obsidian2.stringifyYaml)(fm)}---

${body}`;
}
function deriveId(data, fileName) {
  if (data && typeof data.id === "string" && data.id.trim()) return data.id.trim();
  return fileName.replace(/\.md$/, "");
}
function numOr(v, fallback, now) {
  if (typeof v === "number" && isFinite(v)) return v;
  if (typeof v === "string" && v.trim()) {
    const parsed = Date.parse(v);
    if (!isNaN(parsed)) return parsed;
    const num = Number(v);
    if (isFinite(num)) return num;
  }
  return isFinite(fallback) ? fallback : now;
}
var CardService = class {
  constructor(app, getCardsFolder) {
    this.app = app;
    this.getCardsFolder = getCardsFolder;
  }
  folder() {
    return this.getCardsFolder().trim().replace(/^\/+|\/+$/g, "");
  }
  isCardPath(path) {
    const f = this.folder();
    return f.length > 0 && path.startsWith(f + "/") && path.endsWith(".md");
  }
  /** 确保文件夹存在（不存在则创建） */
  async ensureFolder(folder) {
    const clean = folder.trim().replace(/^\/+|\/+$/g, "");
    if (!clean) return;
    if (!this.app.vault.getAbstractFileByPath(clean)) {
      try {
        await this.app.vault.createFolder(clean);
      } catch (e) {
      }
    }
  }
  getFile(path) {
    const f = this.app.vault.getAbstractFileByPath(path);
    return f instanceof import_obsidian2.TFile ? f : null;
  }
  /** 读取单张卡片（cachedRead 走插件读缓存，热路径安全） */
  async readCard(file) {
    const content = await this.app.vault.cachedRead(file);
    const { data, body } = splitFrontmatter(content);
    return this.buildCard(file, data, body);
  }
  buildCard(file, data, body) {
    const trimmed = body.trim();
    return {
      id: deriveId(data, file.name),
      path: file.path,
      title: data && typeof data.title === "string" && data.title.trim() ? data.title.trim() : void 0,
      tags: normalizeTags(data == null ? void 0 : data.tags),
      created: numOr(data == null ? void 0 : data.created, file.stat.ctime, Date.now()),
      updated: numOr(data == null ? void 0 : data.updated, file.stat.mtime, Date.now()),
      parent: data && typeof data.parent === "string" && data.parent.trim() ? data.parent.trim() : void 0,
      children: Array.isArray(data == null ? void 0 : data.children) ? data.children.filter((c) => typeof c === "string") : [],
      archived: (data == null ? void 0 : data.archived) === true,
      snippet: trimmed.slice(0, SNIPPET_LENGTH),
      hasTaskList: /^\s*[-*] \[[ xX]\]/m.test(body),
      mtime: file.stat.mtime
    };
  }
  /** 新建卡片，返回新文件（空正文返回 null） */
  async createCard(opts) {
    const body = opts.body.trim();
    if (!body) return null;
    const now = Date.now();
    const id = generateId(now);
    await this.ensureFolder(this.folder());
    const path = `${this.folder()}/${id}.md`;
    const fm = { id, created: now, updated: now };
    if (opts.title) fm.title = opts.title;
    if (opts.tags && opts.tags.length) fm.tags = opts.tags;
    if (opts.parent) fm.parent = opts.parent;
    await this.app.vault.create(path, buildCardContent(fm, body));
    return this.getFile(path);
  }
  /** 批量追加标签（顺序 await） */
  async setTags(cards, tagsToAdd) {
    const clean = [...new Set(normalizeTags(tagsToAdd))];
    if (!clean.length) return;
    for (const card of cards) {
      const file = this.getFile(card.path);
      if (!file) continue;
      await this.app.fileManager.processFrontMatter(file, (fm) => {
        fm.tags = [.../* @__PURE__ */ new Set([...normalizeTags(fm.tags), ...clean])];
        fm.updated = Date.now();
      });
    }
  }
  /** 批量归档 / 取消归档 */
  async setArchived(cards, archived) {
    for (const card of cards) {
      const file = this.getFile(card.path);
      if (!file) continue;
      await this.app.fileManager.processFrontMatter(file, (fm) => {
        fm.archived = archived;
        fm.updated = Date.now();
      });
    }
  }
  /** 批量删除（进 Obsidian 回收站） */
  async deleteCards(cards) {
    for (const card of cards) {
      const file = this.getFile(card.path);
      if (file) await this.app.vault.trash(file, false);
    }
  }
  /** 在父卡片 frontmatter 中登记子卡片 */
  async addChild(parent, child) {
    const file = this.getFile(parent.path);
    if (!file) return;
    await this.app.fileManager.processFrontMatter(file, (fm) => {
      const children = Array.isArray(fm.children) ? fm.children.filter((c) => typeof c === "string") : [];
      if (!children.includes(child.id)) children.push(child.id);
      fm.children = children;
      fm.updated = Date.now();
    });
  }
  /** 读取卡片完整正文（合并成文用；索引里的 Card 只有 snippet） */
  async readBody(card) {
    const file = this.getFile(card.path);
    if (!file) return "";
    const content = await this.app.vault.cachedRead(file);
    const { body } = splitFrontmatter(content);
    return body;
  }
  /** 将卡片 updated 刷新为当前时间（由索引在检测到正文变更时调用） */
  async bumpUpdated(card) {
    const file = this.getFile(card.path);
    if (!file) return;
    await this.app.fileManager.processFrontMatter(file, (fm) => {
      fm.updated = Date.now();
    });
  }
};

// src/index.ts
var import_obsidian3 = require("obsidian");
var SCAN_CONCURRENCY = 10;
var UPDATE_BUMP_THRESHOLD_MS = 1e3;
var UPDATE_BUMP_COOLDOWN_MS = 1500;
var CardIndex = class {
  constructor(app, service, getFolder) {
    this.app = app;
    this.service = service;
    this.getFolder = getFolder;
    this.cardsById = /* @__PURE__ */ new Map();
    this.pathToId = /* @__PURE__ */ new Map();
    this.tagCounts = /* @__PURE__ */ new Map();
    this.sorted = [];
    this.needsSort = true;
    this.listeners = /* @__PURE__ */ new Set();
    this.eventRefs = [];
    this.refreshQueues = /* @__PURE__ */ new Map();
    this.debounceTimers = /* @__PURE__ */ new Map();
    this.lastBump = /* @__PURE__ */ new Map();
    this.isIndexing = false;
    this.ready = false;
  }
  attach() {
    const { metadataCache, vault } = this.app;
    const register = (emitter, ref) => {
      this.eventRefs.push({ emitter, ref });
      return ref;
    };
    register(metadataCache, metadataCache.on("ready", () => void this.build()));
    register(
      metadataCache,
      metadataCache.on("changed", (file) => {
        if (file instanceof import_obsidian3.TFile && this.service.isCardPath(file.path)) this.scheduleRefresh(file.path, 0);
      })
    );
    register(
      vault,
      vault.on("create", (file) => {
        if (file instanceof import_obsidian3.TFile && this.service.isCardPath(file.path)) this.scheduleRefresh(file.path, 0);
      })
    );
    register(
      vault,
      vault.on("modify", (file) => {
        if (file instanceof import_obsidian3.TFile && this.service.isCardPath(file.path)) this.scheduleRefresh(file.path, 500);
      })
    );
    register(
      vault,
      vault.on("delete", (file) => {
        if (this.service.isCardPath(file.path)) this.removeByPath(file.path);
      })
    );
    register(
      vault,
      vault.on("rename", (file, oldPath) => {
        if (this.service.isCardPath(oldPath)) this.removeByPath(oldPath);
        if (file instanceof import_obsidian3.TFile && this.service.isCardPath(file.path)) this.scheduleRefresh(file.path, 0);
      })
    );
  }
  detach() {
    for (const { emitter, ref } of this.eventRefs) emitter.offref(ref);
    this.eventRefs = [];
    for (const timer of this.debounceTimers.values()) window.clearTimeout(timer);
    this.debounceTimers.clear();
  }
  // ---------- 全量构建 ----------
  async build() {
    this.isIndexing = true;
    this.notify();
    const files = this.app.vault.getMarkdownFiles().filter((f) => this.service.isCardPath(f.path));
    const results = [];
    let i = 0;
    const worker = async () => {
      while (i < files.length) {
        const file = files[i++];
        try {
          results.push(await this.service.readCard(file));
        } catch (e) {
        }
      }
    };
    const workers = Array.from({ length: Math.min(SCAN_CONCURRENCY, Math.max(1, files.length)) }, () => worker());
    await Promise.all(workers);
    this.cardsById.clear();
    this.pathToId.clear();
    this.tagCounts.clear();
    for (const card of results) {
      this.cardsById.set(card.id, card);
      this.pathToId.set(card.path, card.id);
      this.addTagCounts(card, 1);
    }
    this.needsSort = true;
    this.isIndexing = false;
    this.ready = true;
    this.notify();
  }
  // ---------- 增量更新 ----------
  scheduleRefresh(path, delay) {
    if (delay <= 0) {
      this.refresh(path);
      return;
    }
    const existing = this.debounceTimers.get(path);
    if (existing !== void 0) window.clearTimeout(existing);
    const timer = window.setTimeout(() => {
      this.debounceTimers.delete(path);
      this.refresh(path);
    }, delay);
    this.debounceTimers.set(path, timer);
  }
  refresh(path) {
    var _a;
    const prev = (_a = this.refreshQueues.get(path)) != null ? _a : Promise.resolve();
    const next = prev.catch(() => void 0).then(async () => {
      const file = this.app.vault.getAbstractFileByPath(path);
      if (!(file instanceof import_obsidian3.TFile)) return;
      let card;
      try {
        card = await this.service.readCard(file);
      } catch (e) {
        return;
      }
      this.maybeBumpUpdated(card);
      this.upsertCard(card);
    });
    this.refreshQueues.set(path, next);
  }
  /** 正文被外部编辑时，回写 updated（带冷却与阈值，防止与自身写入形成循环） */
  maybeBumpUpdated(card) {
    var _a;
    const now = Date.now();
    if (card.mtime - card.updated < UPDATE_BUMP_THRESHOLD_MS) return;
    const last = (_a = this.lastBump.get(card.path)) != null ? _a : 0;
    if (now - last < UPDATE_BUMP_COOLDOWN_MS) return;
    this.lastBump.set(card.path, now);
    this.service.bumpUpdated(card).catch(() => void 0);
  }
  upsertCard(card) {
    const old = this.cardsById.get(card.id);
    if (old && old.path !== card.path) this.pathToId.delete(old.path);
    if (old) this.addTagCounts(old, -1);
    this.cardsById.set(card.id, card);
    this.pathToId.set(card.path, card.id);
    this.addTagCounts(card, 1);
    this.needsSort = true;
    this.notify();
  }
  removeByPath(path) {
    const id = this.pathToId.get(path);
    const card = id ? this.cardsById.get(id) : void 0;
    if (id && card) {
      this.cardsById.delete(id);
      this.addTagCounts(card, -1);
    }
    this.pathToId.delete(path);
    this.needsSort = true;
    this.notify();
  }
  addTagCounts(card, delta) {
    var _a;
    for (const tag of card.tags) {
      const parts = tag.split("/");
      let prefix = "";
      for (const p of parts) {
        prefix = prefix ? `${prefix}/${p}` : p;
        const cur = (_a = this.tagCounts.get(prefix)) != null ? _a : 0;
        const next = cur + delta;
        if (next <= 0) this.tagCounts.delete(prefix);
        else this.tagCounts.set(prefix, next);
      }
    }
  }
  // ---------- 查询 ----------
  all() {
    this.ensureSorted();
    return this.sorted;
  }
  getById(id) {
    return this.cardsById.get(id);
  }
  byPath(path) {
    const id = this.pathToId.get(path);
    return id ? this.cardsById.get(id) : void 0;
  }
  allTags() {
    const out = [];
    for (const [tag, count] of this.tagCounts) out.push({ tag, count });
    out.sort((a, b) => b.count - a.count || a.tag.localeCompare(b.tag, "zh"));
    return out;
  }
  search(query, filter, sort) {
    const qs = query.trim().toLowerCase().split(/\s+/).filter(Boolean);
    const result = this.all().filter((card) => {
      var _a;
      if (!this.matchesFilter(card, filter)) return false;
      if (qs.length) {
        const hay = `${(_a = card.title) != null ? _a : ""} ${card.tags.join(" ")} ${card.snippet}`.toLowerCase();
        if (!qs.every((p) => hay.includes(p))) return false;
      }
      return true;
    });
    if (sort !== "created-desc") result.sort(sortCards(sort));
    return result;
  }
  /** 批量操作后手动刷新（事件可能漏掉时兜底） */
  refreshPaths(paths) {
    for (const p of paths) this.scheduleRefresh(p, 0);
  }
  // ---------- 内部 ----------
  ensureSorted() {
    if (!this.needsSort) return;
    const arr = Array.from(this.cardsById.values());
    arr.sort((a, b) => b.created - a.created || a.id.localeCompare(b.id));
    this.sorted = arr;
    this.needsSort = false;
  }
  matchesFilter(card, f) {
    if (f.hasTag && card.tags.length === 0) return false;
    if (f.noTag && card.tags.length > 0) return false;
    if (f.emptyContent && card.snippet.trim() !== "") return false;
    if (f.hasTaskList && !card.hasTaskList) return false;
    if (!f.showArchived && card.archived) return false;
    if (f.selectedTags.size) {
      let ok = false;
      for (const sel of f.selectedTags) {
        if (card.tags.some((t) => t === sel || t.startsWith(sel + "/"))) {
          ok = true;
          break;
        }
      }
      if (!ok) return false;
    }
    return true;
  }
  // ---------- 变更订阅 ----------
  onChanged(cb) {
    this.listeners.add(cb);
  }
  offChanged(cb) {
    this.listeners.delete(cb);
  }
  notify() {
    for (const cb of this.listeners) cb();
  }
};
function sortCards(sort) {
  const collator = new Intl.Collator("zh");
  switch (sort) {
    case "created-asc":
      return (a, b) => a.created - b.created || a.id.localeCompare(b.id);
    case "updated-desc":
      return (a, b) => b.updated - a.updated || b.created - a.created;
    case "title":
      return (a, b) => {
        var _a, _b;
        return collator.compare((_a = a.title) != null ? _a : a.snippet, (_b = b.title) != null ? _b : b.snippet);
      };
    case "created-desc":
    default:
      return (a, b) => b.created - a.created || a.id.localeCompare(b.id);
  }
}

// src/view/CardBoxView.ts
var import_obsidian9 = require("obsidian");

// src/types.ts
function defaultFilterState(settings) {
  return {
    query: "",
    selectedTags: /* @__PURE__ */ new Set(),
    hasTag: false,
    noTag: false,
    emptyContent: false,
    hasTaskList: false,
    showArchived: settings.showArchived
  };
}

// src/view/CardTile.ts
var import_obsidian4 = require("obsidian");
var HOLD_MS = 500;
function firstLine(s) {
  const line = s.split("\n")[0].trim();
  return line;
}
function buildCardTile(opts) {
  const { card } = opts;
  const el = createDiv({ cls: "cardbox-tile" });
  el.setAttribute("data-card-id", card.id);
  el.style.setProperty("--depth", String(opts.depth));
  if (card.archived) el.addClass("is-archived");
  if (opts.depth > 0) el.addClass("is-child");
  if (opts.selected) el.addClass("is-selected");
  const main = el.createDiv({ cls: "cardbox-tile-main" });
  if (opts.hasVisibleChildren) {
    const expand = main.createEl("button", {
      cls: "cardbox-expand-btn",
      attr: { "aria-label": opts.expanded ? i18n.collapseChildren : i18n.expandChildren }
    });
    (0, import_obsidian4.setIcon)(expand, opts.expanded ? "chevron-down" : "chevron-right");
    expand.addEventListener("click", (e) => {
      e.stopPropagation();
      opts.onToggleExpand(card);
    });
  }
  const check = main.createDiv({ cls: "cardbox-check" });
  if (opts.selected) check.addClass("is-checked");
  const body = main.createDiv({ cls: "cardbox-tile-body" });
  const textRow = body.createDiv({ cls: "cardbox-tile-text" });
  const line = firstLine(card.snippet);
  const titleEl = textRow.createSpan({ cls: "cardbox-tile-title" });
  titleEl.setText(card.title ? card.title : line || i18n.emptyContent);
  if (!card.title && !line) titleEl.addClass("is-empty");
  if (card.title && card.snippet.trim()) {
    body.createSpan({ cls: "cardbox-tile-snippet" }).setText(card.snippet.trim());
  }
  const iconRow = textRow.createSpan({ cls: "cardbox-tile-icons" });
  if (card.hasTaskList) {
    const ic = iconRow.createSpan({ cls: "cardbox-tile-icon" });
    (0, import_obsidian4.setIcon)(ic, "list-checks");
    ic.setAttribute("aria-label", i18n.taskIndicator);
  }
  if (card.archived) {
    const ic = iconRow.createSpan({ cls: "cardbox-tile-icon" });
    (0, import_obsidian4.setIcon)(ic, "archive");
    ic.setAttribute("aria-label", i18n.archivedIndicator);
  }
  const meta = body.createDiv({ cls: "cardbox-tile-meta" });
  for (const tag of card.tags.slice(0, 4)) {
    meta.createSpan({ cls: "cardbox-chip cardbox-chip-sm", text: `#${tag}` });
  }
  meta.createSpan({ cls: "cardbox-tile-time", text: formatRelativeTime(card.created) });
  const more = main.createEl("button", {
    cls: "cardbox-more-btn",
    attr: { "aria-label": i18n.more }
  });
  (0, import_obsidian4.setIcon)(more, "more-horizontal");
  more.addEventListener("click", (e) => {
    e.stopPropagation();
    opts.onKebab(card, more);
  });
  main.addEventListener("click", (e) => {
    e.stopPropagation();
    if (e.target.closest("button")) return;
    opts.onClick(card);
  });
  let pressed = false;
  let pressTimer;
  let startX = 0;
  let startY = 0;
  const clearPress = () => {
    pressed = false;
    if (pressTimer !== void 0) {
      window.clearTimeout(pressTimer);
      pressTimer = void 0;
    }
  };
  el.addEventListener("pointerdown", (e) => {
    if (e.target.closest("button")) return;
    if (e.pointerType === "mouse" && e.button !== 0) return;
    pressed = true;
    startX = e.clientX;
    startY = e.clientY;
    pressTimer = window.setTimeout(() => {
      pressTimer = void 0;
      if (pressed) {
        pressed = false;
        opts.onLongPress(card);
      }
    }, HOLD_MS);
  });
  el.addEventListener("pointermove", (e) => {
    if (!pressed) return;
    const dx = e.clientX - startX;
    const dy = e.clientY - startY;
    if (dx * dx + dy * dy > 100) clearPress();
  });
  el.addEventListener("pointerup", clearPress);
  el.addEventListener("pointercancel", clearPress);
  el.addEventListener("contextmenu", (e) => e.preventDefault());
  return el;
}
function updateTileSelection(el, selected) {
  el.toggleClass("is-selected", selected);
  const check = el.querySelector(".cardbox-check");
  if (check) check.toggleClass("is-checked", selected);
}

// src/utils/dom.ts
function debounce(fn, ms) {
  let timer;
  return (...args) => {
    if (timer !== void 0) window.clearTimeout(timer);
    timer = window.setTimeout(() => {
      timer = void 0;
      fn(...args);
    }, ms);
  };
}

// src/view/FilterBar.ts
var TOGGLE_DEFS = [
  { key: "hasTag", label: i18n.hasTag },
  { key: "noTag", label: i18n.noTag },
  { key: "emptyContent", label: i18n.emptyContent },
  { key: "hasTaskList", label: i18n.hasTask },
  { key: "showArchived", label: i18n.showArchived }
];
var FilterBar = class {
  constructor(filter, settings, index, cb) {
    this.settings = settings;
    this.index = index;
    this.cb = cb;
    this.modeBtns = /* @__PURE__ */ new Map();
    this.toggleEls = /* @__PURE__ */ new Map();
    this.filter = filter;
    this.mode = settings.defaultViewMode;
    this.sort = settings.defaultSort;
    this.searchDebounced = debounce((q) => {
      this.filter.query = q;
      this.cb.onFilterChange();
    }, 200);
  }
  getMode() {
    return this.mode;
  }
  getSort() {
    return this.sort;
  }
  build(container) {
    const el = container.createDiv({ cls: "cardbox-filterbar" });
    const modeRow = el.createDiv({ cls: "cardbox-mode-toggle" });
    const mkModeBtn = (mode, label) => {
      const btn = modeRow.createEl("button", { cls: "cardbox-mode-btn", text: label });
      btn.addEventListener("click", () => {
        if (this.mode === mode) return;
        this.mode = mode;
        this.updateModeUI();
        this.cb.onModeChange(mode);
      });
      this.modeBtns.set(mode, btn);
    };
    mkModeBtn("card", i18n.cardMode);
    mkModeBtn("timeline", i18n.timelineMode);
    const searchRow = el.createDiv({ cls: "cardbox-search-row" });
    this.searchInput = searchRow.createEl("input", {
      cls: "cardbox-search-input",
      attr: { type: "search", placeholder: i18n.searchPlaceholder }
    });
    this.searchInput.addEventListener("input", () => this.searchDebounced(this.searchInput.value));
    const clearBtn = searchRow.createEl("button", { cls: "cardbox-search-clear", attr: { "aria-label": "\xD7" } });
    clearBtn.setText("\xD7");
    clearBtn.addEventListener("click", () => {
      this.searchInput.value = "";
      this.searchDebounced("");
    });
    const scroll = el.createDiv({ cls: "cardbox-chips-scroll" });
    this.chipsRow = scroll.createDiv({ cls: "cardbox-chips" });
    const toggles = el.createDiv({ cls: "cardbox-toggles" });
    for (const def of TOGGLE_DEFS) {
      const pill = toggles.createEl("button", { cls: "cardbox-pill", text: def.label });
      pill.addEventListener("click", () => {
        this.filter[def.key] = !this.filter[def.key];
        this.updateToggleUI();
        this.cb.onFilterChange();
      });
      this.toggleEls.set(def.key, pill);
    }
    const sortRow = el.createDiv({ cls: "cardbox-sortrow" });
    const select = sortRow.createEl("select", { cls: "dropdown cardbox-sort-select" });
    const sortOptions = [
      ["created-desc", i18n.sortCreatedDesc],
      ["created-asc", i18n.sortCreatedAsc],
      ["updated-desc", i18n.sortUpdatedDesc],
      ["title", i18n.sortTitle]
    ];
    for (const [value, label] of sortOptions) {
      const opt = select.createEl("option", { text: label });
      opt.value = value;
    }
    select.value = this.sort;
    select.addEventListener("change", () => {
      this.sort = select.value;
      this.cb.onSortChange(this.sort);
    });
    this.updateModeUI();
    this.updateToggleUI();
    this.refreshTags();
    return el;
  }
  /** 索引变化后刷新标签 chips（保留选中状态，不重建整个筛选栏，避免搜索框失焦） */
  refreshTags() {
    if (!this.chipsRow) return;
    this.chipsRow.empty();
    const top = this.index.allTags().slice(0, 24);
    for (const { tag, count } of top) {
      const chip = this.chipsRow.createSpan({ cls: "cardbox-chip" });
      chip.setText(`#${tag} ${count}`);
      chip.toggleClass("is-active", this.filter.selectedTags.has(tag));
      chip.addEventListener("click", () => {
        if (this.filter.selectedTags.has(tag)) this.filter.selectedTags.delete(tag);
        else this.filter.selectedTags.add(tag);
        this.refreshTags();
        this.cb.onFilterChange();
      });
    }
    const add = this.chipsRow.createSpan({ cls: "cardbox-chip cardbox-chip-add", text: i18n.moreTags });
    add.addEventListener("click", () => this.cb.onAddTag());
  }
  updateModeUI() {
    for (const [mode, btn] of this.modeBtns) btn.toggleClass("is-active", this.mode === mode);
  }
  updateToggleUI() {
    for (const [key, el] of this.toggleEls) el.toggleClass("is-active", this.filter[key]);
  }
};

// src/view/IncrementalList.ts
var IncrementalList = class {
  constructor(container, renderItem) {
    this.container = container;
    this.renderItem = renderItem;
    this.observer = null;
    this.items = [];
    this.rendered = 0;
    this.chunk = 50;
    this.sentinel = container.createDiv({ cls: "cardbox-sentinel" });
    if (typeof IntersectionObserver !== "undefined") {
      this.observer = new IntersectionObserver((entries) => {
        if (entries.some((e) => e.isIntersecting)) this.appendNext();
      });
      this.observer.observe(this.sentinel);
    }
  }
  setItems(items) {
    this.items = items;
    this.rendered = 0;
    this.container.empty();
    this.container.appendChild(this.sentinel);
    if (this.observer) {
      this.observer.disconnect();
      this.observer.observe(this.sentinel);
    }
    this.appendNext();
  }
  appendNext() {
    if (this.rendered >= this.items.length) return;
    const frag = document.createDocumentFragment();
    const end = Math.min(this.rendered + this.chunk, this.items.length);
    for (let i = this.rendered; i < end; i++) {
      frag.appendChild(this.renderItem(this.items[i], i));
    }
    this.rendered = end;
    this.container.insertBefore(frag, this.sentinel);
  }
  destroy() {
    var _a;
    (_a = this.observer) == null ? void 0 : _a.disconnect();
    this.observer = null;
  }
};

// src/modals/ConfirmModal.ts
var import_obsidian5 = require("obsidian");
var ConfirmModal = class extends import_obsidian5.Modal {
  constructor(app, opts) {
    super(app);
    this.opts = opts;
  }
  onOpen() {
    var _a;
    this.setTitle(this.opts.title);
    const { contentEl } = this;
    contentEl.empty();
    contentEl.addClass("cardbox-confirm");
    contentEl.createEl("p", { text: this.opts.message });
    const row = contentEl.createDiv({ cls: "cardbox-modal-actions" });
    new import_obsidian5.ButtonComponent(row).setButtonText(i18n.cancel).onClick(() => this.close());
    new import_obsidian5.ButtonComponent(row).setButtonText((_a = this.opts.confirmText) != null ? _a : i18n.confirm).setWarning().onClick(async () => {
      await this.opts.onConfirm();
      this.close();
    });
  }
};

// src/modals/MergeModal.ts
var import_obsidian6 = require("obsidian");
var MergeModal = class extends import_obsidian6.Modal {
  constructor(app, ctx, cards) {
    super(app);
    this.ctx = ctx;
    this.cards = cards;
    this.mode = "simple";
  }
  onOpen() {
    this.setTitle(i18n.mergeTitle);
    const { contentEl } = this;
    contentEl.empty();
    const titleInput = new import_obsidian6.TextComponent(contentEl);
    titleInput.setPlaceholder(i18n.articleTitlePlaceholder).setValue(`\u5361\u7247\u5408\u96C6 ${toDayKey(Date.now())}`);
    titleInput.inputEl.addClass("cardbox-modal-search");
    titleInput.inputEl.addEventListener("keydown", (e) => {
      if (e.key === "Enter") {
        e.preventDefault();
        void this.merge(titleInput.getValue());
      }
    });
    const modeRow = contentEl.createDiv({ cls: "cardbox-setting-row" });
    modeRow.createSpan({ cls: "cardbox-muted", text: i18n.mergeModeLabel });
    new import_obsidian6.DropdownComponent(modeRow).addOption("simple", i18n.mergeModeSimple).addOption("headings", i18n.mergeModeHeadings).setValue(this.mode).onChange((v) => {
      this.mode = v;
    });
    contentEl.createEl("p", { cls: "cardbox-muted", text: i18n.selectedCount(this.cards.length) });
    const actions = contentEl.createDiv({ cls: "cardbox-modal-actions" });
    new import_obsidian6.ButtonComponent(actions).setButtonText(i18n.cancel).onClick(() => this.close());
    new import_obsidian6.ButtonComponent(actions).setButtonText(i18n.mergeButton).setCta().onClick(() => void this.merge(titleInput.getValue()));
  }
  async merge(rawTitle) {
    const title = rawTitle.trim() || `\u5361\u7247\u5408\u96C6 ${toDayKey(Date.now())}`;
    const bodies = await Promise.all(this.cards.map((c) => this.ctx.service.readBody(c)));
    const content = this.buildArticle(title, bodies);
    const folder = this.ctx.settings.mergeOutputFolder.trim().replace(/^\/+|\/+$/g, "");
    const fileName = sanitizeFileName(title) || toDayKey(Date.now());
    const path = `${folder}/${fileName}.md`;
    try {
      await this.ctx.service.ensureFolder(folder);
      const file = await this.app.vault.create(path, content);
      new import_obsidian6.Notice(i18n.mergedNotice(title), 2e3);
      await this.ctx.openFile(file);
      this.close();
    } catch (err) {
      new import_obsidian6.Notice(String(err));
    }
  }
  buildArticle(title, bodies) {
    const fm = {
      created: Date.now(),
      source: "cardbox-merge",
      sourceCards: this.cards.map((c) => c.id)
    };
    let body;
    if (this.mode === "headings") {
      body = this.cards.map((card, i) => {
        var _a;
        return `## ${i + 1}. ${(_a = card.title) != null ? _a : "\u5361\u7247\u7247\u6BB5"}

${bodies[i].trim()}`;
      }).join("\n\n");
    } else {
      body = this.cards.map((card, i) => `> \u{1F4CE} \u6765\u6E90\u5361\u7247\uFF1A[[${card.id}]]

${bodies[i].trim()}`).join("\n\n---\n\n");
    }
    return `${buildCardContent(fm, `# ${title}

${body}`)}`;
  }
};

// src/modals/TagModal.ts
var import_obsidian7 = require("obsidian");
var TagModal = class extends import_obsidian7.Modal {
  constructor(app, ctx, cards) {
    super(app);
    this.ctx = ctx;
    this.cards = cards;
  }
  onOpen() {
    this.setTitle(i18n.tagTitle);
    const { contentEl } = this;
    contentEl.empty();
    const input = new import_obsidian7.TextComponent(contentEl);
    input.setPlaceholder(i18n.tagPlaceholder).inputEl.addClass("cardbox-modal-search");
    input.inputEl.addEventListener("keydown", (e) => {
      if (e.key === "Enter") {
        e.preventDefault();
        void this.apply(input.getValue());
      }
    });
    const existing = contentEl.createEl("p", { cls: "cardbox-muted", text: i18n.existingTags });
    const chipRow = contentEl.createDiv({ cls: "cardbox-chips" });
    for (const { tag } of this.ctx.index.allTags()) {
      const chip = chipRow.createSpan({ cls: "cardbox-chip" });
      chip.setText(`#${tag}`);
      chip.onclick = () => void this.apply(tag);
    }
    if (!chipRow.children.length) existing.detach();
    const actions = contentEl.createDiv({ cls: "cardbox-modal-actions" });
    new import_obsidian7.ButtonComponent(actions).setButtonText(i18n.cancel).onClick(() => this.close());
    new import_obsidian7.ButtonComponent(actions).setButtonText(i18n.apply).setCta().onClick(() => void this.apply(input.getValue()));
    input.inputEl.focus();
  }
  async apply(raw) {
    const tag = normalizeTag(raw);
    if (!tag) {
      new import_obsidian7.Notice(i18n.emptyCaptureHint, 1500);
      return;
    }
    await this.ctx.service.setTags(this.cards, [tag]);
    this.ctx.index.refreshPaths(this.cards.map((c) => c.path));
    new import_obsidian7.Notice(i18n.tagApplied(this.cards.length, tag), 2e3);
    this.close();
  }
};

// src/modals/TagPickerModal.ts
var import_obsidian8 = require("obsidian");
var TagPickerModal = class extends import_obsidian8.Modal {
  constructor(app, index) {
    super(app);
    this.index = index;
  }
  setOnPick(cb) {
    this.onPick = cb;
    return this;
  }
  onOpen() {
    this.setTitle(i18n.batchTag);
    const { contentEl } = this;
    contentEl.empty();
    const search = new import_obsidian8.TextComponent(contentEl);
    search.setPlaceholder(i18n.searchPlaceholder).inputEl.addClass("cardbox-modal-search");
    const listEl = contentEl.createDiv({ cls: "cardbox-tag-picker" });
    this.render(listEl, "");
    search.onChange((q) => this.render(listEl, q));
  }
  render(listEl, query) {
    listEl.empty();
    const q = query.trim().toLowerCase();
    const tags = this.index.allTags().filter((t) => !q || t.tag.toLowerCase().includes(q)).sort((a, b) => b.count - a.count);
    for (const { tag, count } of tags) {
      const row = listEl.createDiv({ cls: "cardbox-tag-row" });
      const label = row.createSpan({ cls: "cardbox-chip" });
      label.setText(`#${tag}`);
      row.createSpan({ cls: "cardbox-tag-count", text: String(count) });
      row.onclick = () => {
        var _a;
        (_a = this.onPick) == null ? void 0 : _a.call(this, tag);
        this.close();
      };
    }
    if (!tags.length) listEl.createEl("p", { cls: "cardbox-muted", text: i18n.noMatch });
  }
};

// src/view/CardBoxView.ts
var CARD_BOX_VIEW_TYPE = "cardbox-main";
var CardBoxView = class extends import_obsidian9.ItemView {
  constructor(leaf, ctx) {
    super(leaf);
    this.selectionMode = false;
    this.selectedIds = /* @__PURE__ */ new Set();
    this.expandedIds = /* @__PURE__ */ new Set();
    this.renderKey = "";
    this.raf = 0;
    this.indexChangedCb = () => this.scheduleRender();
    this.ctx = ctx;
    this.filter = defaultFilterState(ctx.settings);
  }
  getViewType() {
    return CARD_BOX_VIEW_TYPE;
  }
  getDisplayText() {
    return i18n.viewTitle;
  }
  getIcon() {
    return "boxes";
  }
  async onOpen() {
    const root = this.contentEl;
    root.empty();
    root.addClass("cardbox-root");
    this.content = root;
    this.filterBar = new FilterBar(
      this.filter,
      this.ctx.settings,
      this.ctx.index,
      {
        onFilterChange: () => this.scheduleRender(),
        onModeChange: () => this.scheduleRender(),
        onSortChange: () => this.scheduleRender(),
        onAddTag: () => {
          new TagPickerModal(this.app, this.ctx.index).setOnPick((tag) => {
            this.filter.selectedTags.add(tag);
            this.filterBar.refreshTags();
            this.scheduleRender();
          }).open();
        }
      }
    );
    this.filterBar.build(root);
    const actionRow = root.createDiv({ cls: "cardbox-actionbar" });
    const newBtn = actionRow.createEl("button", { cls: "cardbox-action-btn", attr: { "aria-label": i18n.newCard } });
    (0, import_obsidian9.setIcon)(newBtn, "plus");
    newBtn.addEventListener("click", () => this.ctx.openCapture());
    const selectBtn = actionRow.createEl("button", { cls: "cardbox-action-btn", attr: { "aria-label": i18n.toggleSelect } });
    (0, import_obsidian9.setIcon)(selectBtn, "check-square");
    selectBtn.addEventListener("click", () => this.toggleSelectionMode());
    this.selectionBarEl = root.createDiv({ cls: "cardbox-selectionbar" });
    this.placeholderEl = root.createDiv({ cls: "cardbox-placeholder" });
    this.listEl = root.createDiv({ cls: "cardbox-list" });
    this.list = new IncrementalList(this.listEl, (item) => this.renderItem(item));
    this.ctx.index.onChanged(this.indexChangedCb);
    this.filterBar.refreshTags();
    this.scheduleRender();
  }
  onClose() {
    var _a;
    this.ctx.index.offChanged(this.indexChangedCb);
    (_a = this.list) == null ? void 0 : _a.destroy();
    if (this.raf) window.cancelAnimationFrame(this.raf);
    return Promise.resolve();
  }
  // ---------- 对外操作（供命令调用） ----------
  isSelectionModeAvailable() {
    return true;
  }
  getSelectedCards() {
    const out = [];
    for (const id of this.selectedIds) {
      const card = this.ctx.index.getById(id);
      if (card) out.push(card);
    }
    return out;
  }
  toggleSelectionMode() {
    this.selectionMode = !this.selectionMode;
    if (!this.selectionMode) this.selectedIds.clear();
    this.updateSelectionUI();
  }
  mergeSelected() {
    const cards = this.getSelectedCards();
    if (cards.length) new MergeModal(this.app, this.ctx, cards).open();
  }
  batchTagSelected() {
    const cards = this.getSelectedCards();
    if (cards.length) new TagModal(this.app, this.ctx, cards).open();
  }
  archiveSelected() {
    this.archiveCards(this.getSelectedCards(), true);
  }
  deleteSelected() {
    this.deleteCards(this.getSelectedCards());
  }
  // ---------- 渲染 ----------
  scheduleRender() {
    if (this.raf) window.cancelAnimationFrame(this.raf);
    this.raf = window.requestAnimationFrame(() => {
      this.raf = 0;
      this.render();
    });
  }
  render() {
    if (this.ctx.index.isIndexing && !this.ctx.index.ready) {
      this.showPlaceholder(i18n.indexing);
      return;
    }
    const mode = this.filterBar.getMode();
    const sort = this.filterBar.getSort();
    const filtered = this.ctx.index.search(this.filter.query, this.filter, sort);
    if (filtered.length === 0) {
      const hasFilters = this.filter.query.trim() !== "" || this.filter.selectedTags.size > 0 || this.filter.hasTag || this.filter.noTag || this.filter.emptyContent || this.filter.hasTaskList;
      this.showPlaceholder(hasFilters ? i18n.noMatch : i18n.empty);
      return;
    }
    this.placeholderEl.empty();
    this.placeholderEl.addClass("is-hidden");
    this.listEl.removeClass("is-hidden");
    const key = mode + "|" + sort + "|" + this.filter.query + "|" + [...this.filter.selectedTags].sort().join(",") + "|" + [this.filter.hasTag, this.filter.noTag, this.filter.emptyContent, this.filter.hasTaskList, this.filter.showArchived].map(String).join(",") + "|" + filtered.map((c) => c.id).join(",");
    if (key === this.renderKey) return;
    this.renderKey = key;
    const items = mode === "card" ? this.buildCardItems(filtered) : this.buildDayItems(filtered);
    this.list.setItems(items);
  }
  showPlaceholder(text) {
    this.renderKey = "";
    this.listEl.addClass("is-hidden");
    this.placeholderEl.removeClass("is-hidden");
    this.placeholderEl.setText(text);
  }
  buildCardItems(filtered) {
    const byId = new Map(filtered.map((c) => [c.id, c]));
    const expanded = this.expandedIds;
    const result = [];
    const visited = /* @__PURE__ */ new Set();
    const visit = (card, depth) => {
      if (visited.has(card.id)) return;
      visited.add(card.id);
      const children = card.children.map((id) => byId.get(id)).filter((c) => !!c);
      const isExpanded = children.length > 0 && expanded.has(card.id);
      result.push({ kind: "card", card, depth, expanded: isExpanded, hasVisibleChildren: children.length > 0 });
      if (isExpanded) for (const child of children) visit(child, depth + 1);
    };
    for (const card of filtered) {
      const parent = card.parent ? byId.get(card.parent) : void 0;
      const parentExpanded = parent !== void 0 && expanded.has(parent.id);
      if (!parent || !parentExpanded) visit(card, 0);
    }
    return result;
  }
  buildDayItems(filtered) {
    const groups = /* @__PURE__ */ new Map();
    for (const card of filtered) {
      const day = (/* @__PURE__ */ new Date(toDayKey(card.created) + "T00:00:00")).getTime();
      const arr = groups.get(day);
      if (arr) arr.push(card);
      else groups.set(day, [card]);
    }
    const days = Array.from(groups.keys()).sort((a, b) => b - a);
    return days.map((day) => ({ kind: "day", day, cards: groups.get(day) }));
  }
  renderItem(item) {
    if (item.kind === "card") return this.buildTile(item.card, item.depth, item.expanded, item.hasVisibleChildren);
    const group = createDiv({ cls: "cardbox-day-group" });
    const header = group.createDiv({ cls: "cardbox-day-header" });
    header.setText(formatDayHeader(item.day));
    const cards = item.cards.slice().sort((a, b) => b.created - a.created);
    for (const card of cards) group.appendChild(this.buildTile(card, 0, false, false));
    return group;
  }
  buildTile(card, depth, expanded, hasVisibleChildren) {
    return buildCardTile({
      card,
      depth,
      selected: this.selectedIds.has(card.id),
      expanded,
      hasVisibleChildren,
      onClick: (c) => this.onTileClick(c),
      onLongPress: (c) => this.onTileLongPress(c),
      onToggleExpand: (c) => {
        if (this.expandedIds.has(c.id)) this.expandedIds.delete(c.id);
        else this.expandedIds.add(c.id);
        this.renderKey = "";
        this.scheduleRender();
      },
      onKebab: (c, anchor) => this.showCardMenu(c, anchor)
    });
  }
  // ---------- 交互 ----------
  onTileClick(card) {
    if (this.selectionMode) {
      this.toggleSelect(card);
    } else {
      void this.openCard(card);
    }
  }
  onTileLongPress(card) {
    if (!this.selectionMode) {
      this.selectionMode = true;
      this.updateSelectionUI();
    }
    this.toggleSelect(card, true);
  }
  toggleSelect(card, forceSelect = false) {
    if (forceSelect) {
      if (this.selectedIds.has(card.id)) return;
      this.selectedIds.add(card.id);
    } else if (this.selectedIds.has(card.id)) {
      this.selectedIds.delete(card.id);
    } else {
      this.selectedIds.add(card.id);
    }
    this.updateTileInDom(card.id);
    this.updateSelectionBar();
  }
  updateTileInDom(id) {
    const tile = this.listEl.querySelector(`[data-card-id="${id}"]`);
    if (tile) updateTileSelection(tile, this.selectedIds.has(id));
  }
  updateSelectionUI() {
    this.content.toggleClass("cardbox-is-selecting", this.selectionMode);
    this.selectionBarEl.toggleClass("is-visible", this.selectionMode);
    this.applySelectionToTiles();
    this.updateSelectionBar();
  }
  applySelectionToTiles() {
    const tiles = this.listEl.querySelectorAll(".cardbox-tile");
    tiles.forEach((tile) => {
      const id = tile.getAttribute("data-card-id");
      if (id) updateTileSelection(tile, this.selectedIds.has(id));
    });
  }
  updateSelectionBar() {
    this.selectionBarEl.empty();
    const n = this.selectedIds.size;
    this.selectionBarEl.createSpan({ cls: "cardbox-selection-count", text: i18n.selectedCount(n) });
    const mkBtn = (label, icon, disabled, cb) => {
      const b = new import_obsidian9.ButtonComponent(this.selectionBarEl).setButtonText(label).setIcon(icon);
      if (disabled) b.setDisabled(true);
      b.onClick(cb);
    };
    mkBtn(i18n.tagSelected, "tag", n === 0, () => this.batchTagSelected());
    mkBtn(i18n.mergeSelectedAction, "file-text", n === 0, () => this.mergeSelected());
    mkBtn(i18n.archiveSelectedAction, "archive", n === 0, () => this.archiveSelected());
    mkBtn(i18n.deleteSelectedAction, "trash", n === 0, () => this.deleteSelected());
    const cancel = new import_obsidian9.ButtonComponent(this.selectionBarEl).setButtonText(i18n.cancelSelect);
    cancel.onClick(() => this.toggleSelectionMode());
  }
  async openCard(card) {
    const file = this.app.vault.getAbstractFileByPath(card.path);
    if (file instanceof import_obsidian9.TFile) await this.ctx.openFile(file);
  }
  showCardMenu(card, anchor) {
    const menu = new import_obsidian9.Menu();
    menu.addItem((item) => item.setTitle(i18n.edit).setIcon("pencil").onClick(() => void this.openCard(card)));
    menu.addItem(
      (item) => item.setTitle(i18n.addChild).setIcon("file-plus").onClick(() => this.ctx.openCapture("", card))
    );
    menu.addItem(
      (item) => item.setTitle(i18n.tag).setIcon("tag").onClick(() => new TagModal(this.app, this.ctx, [card]).open())
    );
    if (card.children.length > 0) {
      const expanded = this.expandedIds.has(card.id);
      menu.addItem(
        (item) => item.setTitle(expanded ? i18n.collapseChildren : i18n.expandChildren).setIcon("chevron-down").onClick(() => {
          if (expanded) this.expandedIds.delete(card.id);
          else this.expandedIds.add(card.id);
          this.renderKey = "";
          this.scheduleRender();
        })
      );
    }
    menu.addItem(
      (item) => item.setTitle(card.archived ? i18n.unarchive : i18n.archive).setIcon("archive").onClick(() => this.archiveCards([card], !card.archived))
    );
    menu.addItem(
      (item) => item.setTitle(i18n.delete).setIcon("trash").onClick(() => this.deleteCards([card]))
    );
    const rect = anchor.getBoundingClientRect();
    menu.showAtPosition({ x: rect.left, y: rect.bottom });
  }
  // ---------- 批量操作 ----------
  archiveCards(cards, archived) {
    const run = async () => {
      await this.ctx.service.setArchived(cards, archived);
      this.clearSelectionAfterBatch();
    };
    if (archived) {
      new ConfirmModal(this.app, {
        title: i18n.confirmTitle,
        message: i18n.confirmArchiveText(cards.length),
        onConfirm: run
      }).open();
    } else {
      void run();
    }
  }
  deleteCards(cards) {
    if (!cards.length) return;
    new ConfirmModal(this.app, {
      title: i18n.confirmTitle,
      message: i18n.confirmDeleteText(cards.length),
      onConfirm: async () => {
        await this.ctx.service.deleteCards(cards);
        this.clearSelectionAfterBatch();
      }
    }).open();
  }
  clearSelectionAfterBatch() {
    this.selectedIds.clear();
    if (this.selectionMode) {
      this.selectionMode = false;
      this.updateSelectionUI();
    }
    this.renderKey = "";
    this.scheduleRender();
  }
};
CardBoxView.VIEW_TYPE = CARD_BOX_VIEW_TYPE;

// src/modals/CaptureModal.ts
var import_obsidian10 = require("obsidian");
var CaptureModal = class extends import_obsidian10.Modal {
  constructor(app, ctx, opts = {}) {
    super(app);
    this.ctx = ctx;
    this.opts = opts;
    this.continuous = true;
    this.continuous = ctx.settings.continuousCaptureDefault;
  }
  onOpen() {
    var _a;
    this.setTitle(this.opts.parent ? i18n.addChild : i18n.captureTitle);
    const { contentEl } = this;
    contentEl.empty();
    contentEl.addClass("cardbox-capture");
    this.textarea = contentEl.createEl("textarea", {
      cls: "cardbox-capture-input",
      attr: {
        rows: "6",
        placeholder: (_a = this.opts.placeholder) != null ? _a : i18n.capturePlaceholder,
        "aria-label": this.opts.parent ? i18n.childCapturePlaceholder : i18n.capturePlaceholder
      }
    });
    if (this.opts.prefill) this.textarea.value = this.opts.prefill;
    this.textarea.focus();
    const footer = contentEl.createDiv({ cls: "cardbox-modal-footer" });
    if (this.opts.parent || this.opts.singleShot) {
      this.continuous = false;
    } else {
      new import_obsidian10.ToggleComponent(footer).setValue(this.continuous).setTooltip(i18n.continuousMode).onChange((v) => {
        this.continuous = v;
      });
      footer.createSpan({ cls: "cardbox-muted", text: i18n.continuousMode });
    }
    footer.createDiv({ cls: "cardbox-spacer" });
    new import_obsidian10.ButtonComponent(footer).setButtonText(i18n.cancel).onClick(() => this.close());
    const saveBtn = new import_obsidian10.ButtonComponent(footer).setButtonText(i18n.save).setCta();
    saveBtn.onClick(() => void this.save());
    this.textarea.addEventListener("keydown", (e) => {
      if (e.key === "Enter" && (e.ctrlKey || e.metaKey)) {
        e.preventDefault();
        void this.save();
      }
    });
  }
  async save() {
    const body = this.textarea.value.trim();
    if (!body) {
      new import_obsidian10.Notice(i18n.emptyCaptureHint, 1500);
      return;
    }
    const file = await this.ctx.service.createCard({
      body,
      tags: this.ctx.settings.defaultTags
    });
    if (!file) return;
    if (this.opts.parent) {
      try {
        const child = await this.ctx.service.readCard(file);
        await this.ctx.service.addChild(this.opts.parent, child);
      } catch (e) {
      }
      this.close();
      return;
    }
    if (this.continuous) {
      this.textarea.value = "";
      this.textarea.focus();
    } else {
      this.close();
    }
  }
  onClose() {
    this.contentEl.empty();
  }
};

// src/main.ts
var CardBoxPlugin = class extends import_obsidian11.Plugin {
  constructor() {
    super(...arguments);
    this.settings = DEFAULT_SETTINGS;
  }
  async onload() {
    await this.loadSettings();
    this.service = new CardService(this.app, () => this.settings.cardsFolder);
    this.index = new CardIndex(this.app, this.service, () => this.settings.cardsFolder);
    this.index.attach();
    this.ctx = {
      settings: this.settings,
      index: this.index,
      service: this.service,
      openFile: (file) => this.openFile(file),
      openCapture: (prefill, parent) => this.openCapture(prefill, parent),
      saveSettings: () => this.saveSettings()
    };
    await this.ensureCardsFolder();
    this.registerView(CARD_BOX_VIEW_TYPE, (leaf) => new CardBoxView(leaf, this.ctx));
    this.addRibbonIcon("boxes", i18n.openMain, () => void this.openCardBoxView());
    this.registerCaptureCommands();
    this.addSettingTab(
      new CardBoxSettingTab(this.app, {
        settings: this.settings,
        saveSettings: () => this.saveSettings(),
        onFolderChanged: () => {
          void this.index.build();
        }
      })
    );
    if (!this.index.ready) void this.index.build();
  }
  onunload() {
    this.index.detach();
  }
  // ---------- 命令 ----------
  registerCaptureCommands() {
    this.addCommand({ id: "cardbox:capture", name: i18n.capture, callback: () => this.openCapture() });
    this.addCommand({
      id: "cardbox:open-main",
      name: i18n.openMain,
      callback: () => void this.openCardBoxView()
    });
    this.addCommand({
      id: "cardbox:toggle-select",
      name: i18n.toggleSelect,
      checkCallback: (checking) => {
        const view = this.activeView();
        if (!view) return false;
        if (checking) return true;
        view.toggleSelectionMode();
        return true;
      }
    });
    this.addSelectionCommand("cardbox:merge", i18n.mergeSelected, (view) => view.mergeSelected());
    this.addSelectionCommand("cardbox:batch-tag", i18n.batchTag, (view) => view.batchTagSelected());
    this.addSelectionCommand("cardbox:archive-selected", i18n.archiveSelected, (view) => view.archiveSelected());
    this.addSelectionCommand("cardbox:delete-selected", i18n.deleteSelected, (view) => view.deleteSelected());
  }
  addSelectionCommand(id, name, run) {
    this.addCommand({
      id,
      name,
      checkCallback: (checking) => {
        const view = this.activeView();
        if (!view) return false;
        if (view.getSelectedCards().length === 0) return false;
        if (checking) return true;
        run(view);
        return true;
      }
    });
  }
  activeView() {
    const leaves = this.app.workspace.getLeavesOfType(CARD_BOX_VIEW_TYPE);
    if (!leaves.length) return null;
    const view = leaves[0].view;
    return view instanceof CardBoxView ? view : null;
  }
  // ---------- 打开动作 ----------
  async openCardBoxView() {
    const leaves = this.app.workspace.getLeavesOfType(CARD_BOX_VIEW_TYPE);
    if (leaves.length) {
      this.app.workspace.revealLeaf(leaves[0]);
      return;
    }
    const leaf = this.app.workspace.getLeaf(true);
    await leaf.setViewState({ type: CARD_BOX_VIEW_TYPE, active: true });
    this.app.workspace.revealLeaf(leaf);
  }
  async openFile(file) {
    const leaf = this.app.workspace.getLeaf("tab");
    await leaf.openFile(file);
  }
  openCapture(prefill = "", parent) {
    new CaptureModal(this.app, this.ctx, { prefill, parent }).open();
  }
  async ensureCardsFolder() {
    const folder = this.settings.cardsFolder.trim().replace(/^\/+|\/+$/g, "");
    if (!folder) return;
    if (!this.app.vault.getAbstractFileByPath(folder)) {
      try {
        await this.app.vault.createFolder(folder);
        new import_obsidian11.Notice(i18n.noticeFolderCreated(folder));
      } catch (e) {
      }
    }
  }
  // ---------- 设置 ----------
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
};
