/**
 * 内置常用 lucide 图标清单(Obsidian 内置 lucide 图标库,支持全部 lucide 图标名)。
 * 用户在设置页也可以手动输入任意 lucide 图标名,不局限于本清单。
 */
export interface IconEntry {
	name: string;
	label: string;
}

export const ICON_LIBRARY: IconEntry[] = [
	// 常用操作
	{ name: "command", label: "命令面板" },
	{ name: "search", label: "搜索" },
	{ name: "switcher", label: "快速切换" },
	{ name: "plus", label: "加号" },
	{ name: "file-plus", label: "新建文件" },
	{ name: "folder-plus", label: "新建文件夹" },
	{ name: "file-text", label: "文件" },
	{ name: "file", label: "空白文件" },
	{ name: "files", label: "多文件" },
	{ name: "folder", label: "文件夹" },
	{ name: "book-open", label: "打开书本" },
	{ name: "library", label: "资料库" },
	{ name: "sticky-note", label: "便签" },
	{ name: "notebook-pen", label: "笔记本" },
	{ name: "notebook-tabs", label: "笔记本标签" },
	// 导航与定位
	{ name: "arrow-up", label: "上箭头" },
	{ name: "arrow-down", label: "下箭头" },
	{ name: "arrow-left", label: "左箭头" },
	{ name: "arrow-right", label: "右箭头" },
	{ name: "chevron-up", label: "折叠上" },
	{ name: "chevron-down", label: "折叠下" },
	{ name: "chevrons-up", label: "双上箭头" },
	{ name: "chevrons-down", label: "双下箭头" },
	{ name: "corner-down-left", label: "返回" },
	{ name: "undo-2", label: "撤销" },
	{ name: "redo-2", label: "重做" },
	{ name: "home", label: "主页" },
	{ name: "locate", label: "定位" },
	{ name: "map-pin", label: "地图钉" },
	{ name: "navigation", label: "导航" },
	{ name: "compass", label: "指南针" },
	{ name: "move", label: "移动" },
	{ name: "rotate-ccw", label: "逆时针旋转" },
	{ name: "rotate-cw", label: "顺时针旋转" },
	// 编辑与格式
	{ name: "pencil", label: "编辑" },
	{ name: "pen-line", label: "钢笔" },
	{ name: "highlighter", label: "荧光笔" },
	{ name: "eraser", label: "橡皮擦" },
	{ name: "bold", label: "加粗" },
	{ name: "italic", label: "斜体" },
	{ name: "underline", label: "下划线" },
	{ name: "strikethrough", label: "删除线" },
	{ name: "list", label: "列表" },
	{ name: "list-ordered", label: "有序列表" },
	{ name: "list-checks", label: "检查列表" },
	{ name: "quote", label: "引用" },
	{ name: "code", label: "代码" },
	{ name: "code-2", label: "代码块" },
	{ name: "link", label: "链接" },
	{ name: "link-2", label: "双向链接" },
	{ name: "unlink", label: "取消链接" },
	{ name: "heading-1", label: "标题1" },
	{ name: "heading-2", label: "标题2" },
	{ name: "heading-3", label: "标题3" },
	{ name: "pilcrow", label: "段落" },
	{ name: "table", label: "表格" },
	{ name: "image", label: "图片" },
	{ name: "images", label: "多图" },
	{ name: "camera", label: "相机" },
	{ name: "video", label: "视频" },
	{ name: "mic", label: "麦克风" },
	{ name: "audio-lines", label: "音频" },
	{ name: "scissors", label: "剪切" },
	{ name: "copy", label: "复制" },
	{ name: "clipboard", label: "剪贴板" },
	{ name: "trash", label: "删除" },
	{ name: "trash-2", label: "删除2" },
	{ name: "archive", label: "归档" },
	{ name: "tag", label: "标签" },
	{ name: "tags", label: "多标签" },
	{ name: "star", label: "星标" },
	{ name: "heart", label: "收藏" },
	{ name: "bookmark", label: "书签" },
	{ name: "flag", label: "旗帜" },
	{ name: "pin", label: "置顶" },
	{ name: "paperclip", label: "附件" },
	// 视图与窗口
	{ name: "eye", label: "阅读" },
	{ name: "eye-off", label: "隐藏" },
	{ name: "panel-left", label: "左侧栏" },
	{ name: "panel-right", label: "右侧栏" },
	{ name: "panel-bottom", label: "底部栏" },
	{ name: "layout-dashboard", label: "仪表盘" },
	{ name: "layout-grid", label: "网格" },
	{ name: "layout-list", label: "列表" },
	{ name: "columns-2", label: "双栏" },
	{ name: "rows-2", label: "双行" },
	{ name: "maximize", label: "全屏" },
	{ name: "minimize", label: "还原" },
	{ name: "fullscreen", label: "全屏2" },
	{ name: "square-dashed", label: "白板" },
	{ name: "canvas", label: "画布" },
	{ name: "presentation", label: "演示" },
	{ name: "slides", label: "幻灯片" },
	{ name: "scan", label: "扫描" },
	{ name: "zoom-in", label: "放大" },
	{ name: "zoom-out", label: "缩小" },
	// 时间与日期
	{ name: "calendar", label: "日历" },
	{ name: "calendar-plus", label: "新建日程" },
	{ name: "calendar-check", label: "完成日程" },
	{ name: "clock", label: "时钟" },
	{ name: "timer", label: "计时" },
	{ name: "alarm-clock", label: "闹钟" },
	{ name: "bell", label: "通知" },
	{ name: "history", label: "历史" },
	{ name: "refresh-cw", label: "刷新" },
	// 沟通与外联
	{ name: "external-link", label: "外部链接" },
	{ name: "globe", label: "地球" },
	{ name: "mail", label: "邮件" },
	{ name: "message-square", label: "消息" },
	{ name: "send", label: "发送" },
	{ name: "share-2", label: "分享" },
	{ name: "download", label: "下载" },
	{ name: "upload", label: "上传" },
	{ name: "printer", label: "打印" },
	// 状态与杂项
	{ name: "check", label: "对勾" },
	{ name: "check-circle", label: "圆圈对勾" },
	{ name: "circle", label: "圆圈" },
	{ name: "circle-dot", label: "圆圈点" },
	{ name: "x", label: "叉" },
	{ name: "info", label: "信息" },
	{ name: "help-circle", label: "帮助" },
	{ name: "alert-circle", label: "警告" },
	{ name: "settings", label: "设置" },
	{ name: "sliders-horizontal", label: "调节" },
	{ name: "wrench", label: "扳手" },
	{ name: "hammer", label: "锤子" },
	{ name: "sparkles", label: "星火" },
	{ name: "wand-2", label: "魔棒" },
	{ name: "lightbulb", label: "灯泡" },
	{ name: "zap", label: "闪电" },
	{ name: "flame", label: "火焰" },
	{ name: "target", label: "目标" },
	{ name: "award", label: "奖章" },
	{ name: "trophy", label: "奖杯" },
	{ name: "gem", label: "宝石" },
	{ name: "shield", label: "盾牌" },
	{ name: "lock", label: "锁" },
	{ name: "key", label: "钥匙" },
	{ name: "smartphone", label: "手机" },
	{ name: "tablet", label: "平板" },
	{ name: "laptop", label: "笔记本" },
	{ name: "monitor", label: "显示器" },
	{ name: "watch", label: "手表" },
	{ name: "battery-charging", label: "充电" },
	{ name: "wifi", label: "无线" },
	{ name: "moon", label: "月亮" },
	{ name: "sun", label: "太阳" },
	{ name: "cloud", label: "云" },
	{ name: "cloud-sun", label: "多云" },
	{ name: "umbrella", label: "雨伞" },
	{ name: "leaf", label: "叶子" },
	{ name: "flower-2", label: "花" },
	{ name: "bug", label: "虫子" },
	{ name: "cat", label: "猫" },
	{ name: "dog", label: "狗" },
	{ name: "bird", label: "鸟" },
	{ name: "fish", label: "鱼" },
	{ name: "rocket", label: "火箭" },
	{ name: "plane", label: "飞机" },
	{ name: "car", label: "汽车" },
	{ name: "bike", label: "自行车" },
	{ name: "footprints", label: "脚印" },
	{ name: "coffee", label: "咖啡" },
	{ name: "cup-soda", label: "饮料" },
	{ name: "pizza", label: "披萨" },
	{ name: "apple", label: "苹果" },
	{ name: "gift", label: "礼物" },
	{ name: "party-popper", label: "庆祝" },
	{ name: "music", label: "音乐" },
	{ name: "gamepad-2", label: "游戏" },
	{ name: "dice-5", label: "骰子" },
	{ name: "puzzle", label: "拼图" },
	{ name: "palette", label: "调色板" },
	{ name: "brush", label: "画笔" },
	{ name: "pen-tool", label: "钢笔工具" },
	{ name: "dna", label: "DNA" },
	{ name: "atom", label: "原子" },
	{ name: "flask-conical", label: "烧瓶" },
	{ name: "microscope", label: "显微镜" },
	{ name: "paw-print", label: "爪印" },
	{ name: "sprout", label: "幼苗" },
	{ name: "tree-deciduous", label: "树" },
	{ name: "mountain", label: "山" },
	{ name: "sunrise", label: "日出" },
	{ name: "sunset", label: "日落" },
	{ name: "waves", label: "波浪" },
	{ name: "droplets", label: "水滴" },
	{ name: "snowflake", label: "雪花" },
	{ name: "crown", label: "皇冠" },
];

/** 按关键字过滤图标清单(名称与中文标签) */
export function filterIcons(query: string, limit = 60): IconEntry[] {
	const q = query.trim().toLowerCase();
	if (!q) return ICON_LIBRARY.slice(0, limit);
	const result: IconEntry[] = [];
	for (const entry of ICON_LIBRARY) {
		if (
			entry.name.toLowerCase().includes(q) ||
			entry.label.toLowerCase().includes(q)
		) {
			result.push(entry);
			if (result.length >= limit) break;
		}
	}
	return result;
}

/** 判断是否为常见图标名(允许任意 lucide 名,因此这里只做基础格式校验) */
export function isLikelyIconName(name: string): boolean {
	return /^[a-z0-9-]+$/.test(name.trim());
}
